services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "0.0.0.0:6333:6333"
      - "0.0.0.0:6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  # LangChain Search Service
  langchain-service:
    build: .
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - QDRANT_URL=http://localhost:6333
      - OLLAMA_URL=http://localhost:11434
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  # CHAP2 API Service
  chap2-api:
    build:
      context: ..
      dockerfile: langchain_search_service/Dockerfile.api.simple
    ports:
      - "0.0.0.0:5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5001
      - ASPNETCORE_Kestrel__Endpoints__Http__Url=http://0.0.0.0:5001
    volumes:
      - ../CHAP2.Chorus.Api/data:/app/data
    restart: unless-stopped

  # CHAP2 Web Portal
  chap2-webportal:
    build:
      context: ..
      dockerfile: langchain_search_service/Dockerfile.webportal.simple
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - ASPNETCORE_Kestrel__Endpoints__Http__Url=http://0.0.0.0:5000
      - LangChainService__BaseUrl=http://localhost:8000
      - ApiService__BaseUrl=http://localhost:5001
      - Qdrant__Host=localhost
      - Qdrant__Port=6333
      - Ollama__Host=localhost
      - Ollama__Port=11434
    restart: unless-stopped

volumes:
  qdrant_data: 