services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - chap2-network
    restart: unless-stopped

  # LangChain Search Service with Ollama port forwarding
  langchain-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://localhost:11434
    networks:
      - chap2-network
    volumes:
      - ./data:/app/data
    # Port forwarding to expose host Ollama
    extra_hosts:
      - "ollama-host:127.0.0.1"
    restart: unless-stopped

  # CHAP2 API Service
  chap2-api:
    build:
      context: ..
      dockerfile: langchain_search_service/Dockerfile.api.simple
    ports:
      - "5001:5001"
    depends_on:
      - qdrant
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5001
    networks:
      - chap2-network
    volumes:
      - ../CHAP2.Chorus.Api/data:/app/data
    restart: unless-stopped

  # CHAP2 Web Portal
  chap2-webportal:
    build:
      context: ..
      dockerfile: langchain_search_service/Dockerfile.webportal.simple
    ports:
      - "5000:5000"
    depends_on:
      - chap2-api
      - langchain-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - LangChainService__BaseUrl=http://langchain-service:8000
      - ApiService__BaseUrl=http://chap2-api:5001
      - Qdrant__Host=qdrant
      - Qdrant__Port=6333
      - Ollama__Host=localhost
      - Ollama__Port=11434
    networks:
      - chap2-network
    restart: unless-stopped

networks:
  chap2-network:
    driver: bridge

volumes:
  qdrant_data: 