services:
    # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped


  # Ollama for LLM and Embeddings (with persistent model storage)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama  # Persistent model storage
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped


  # LangChain Search Service
  langchain-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - ollama
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=mistral
      - OLLAMA_EMBEDDING_MODEL=nomic-embed-text
      - COLLECTION_NAME=chorus-vectors
      - VECTOR_SIZE=1536
      - MAX_TOKENS=2048
      - TEMPERATURE=0.7
      - MAX_RESULTS=10
      - MEMORY_CACHE_SIZE=100
      - LOG_LEVEL=INFO
    restart: unless-stopped


  # CHAP2 API Service
  chap2-api:
    build:
      context: ..
      dockerfile: langchain_search_service/Dockerfile.api.simple
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5001
    volumes:
      - ../CHAP2.Chorus.Api/data:/app/data
    restart: unless-stopped


  # CHAP2 Web Portal
  chap2-webportal:
    build:
      context: ..
      dockerfile: langchain_search_service/Dockerfile.webportal.simple
    ports:
      - "5002:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - chap2-api
      - langchain-service
    restart: unless-stopped


volumes:
  qdrant_data:
  ollama_models: 