services:
  # CHAP2 API Service
  chap2-api:
    build:
      context: ../..
      dockerfile: CHAP2.Chorus.Api/Dockerfile
    container_name: chap2-api-local
    ports:
      - "8080:80"    # Host port 8080 → Container port 80 (HTTP only)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - chorus-data:/app/data/chorus
    networks:
      - chap2-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # CHAP2 Web Portal Service
  chap2-web:
    build:
      context: ../..
      dockerfile: CHAP2.UI/CHAP2.WebPortal/Dockerfile
    container_name: chap2-web-local
    ports:
      - "8081:80"    # Host port 8081 → Container port 80 (HTTP only)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApiBaseUrl=http://chap2-api
    depends_on:
      - chap2-api
    networks:
      - chap2-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  chap2-network:
    driver: bridge

volumes:
  chorus-data:
    driver: local 