version: '3.8'

services:
  # CHAP2 API Service
  chap2-api:
    build:
      context: .
      dockerfile: CHAP2.Chorus.Api/Dockerfile
    container_name: chap2-api
    ports:
      - "5000:80"    # Host port 5000 → Container port 80 (HTTP)
      - "7000:443"   # Host port 7000 → Container port 443 (HTTPS)
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80;https://+:443
    volumes:
      - chorus-data:/app/data/chorus
    networks:
      - chap2-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # CHAP2 Web Portal Service
  chap2-web:
    build:
      context: .
      dockerfile: CHAP2.UI/CHAP2.WebPortal/Dockerfile
    container_name: chap2-web
    ports:
      - "5001:80"    # Host port 5001 → Container port 80 (HTTP)
      - "7001:443"   # Host port 7001 → Container port 443 (HTTPS)
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ApiBaseUrl=http://chap2-api
    depends_on:
      - chap2-api
    networks:
      - chap2-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  chap2-network:
    driver: bridge

volumes:
  chorus-data:
    driver: local 